// scripts/apply_template.js
// ---------------------------------------------------
// Purpose: Replace all placeholder HTML files generated by create_structure.js
// with the base template (templates/template-page.html) and inject basic
// page‑specific values (title, description, url). This keeps the site
// modular and ensures every page shares the same SEO‑focused markup.
// ---------------------------------------------------
const fs = require('fs');
const path = require('path');

// Load the base template (as a string)
const templatePath = path.resolve(__dirname, '..', 'templates', 'template-page.html');
const baseTemplate = fs.readFileSync(templatePath, 'utf8');

// Helper to generate a safe title from a file name
function titleFromFile(fileName) {
    // Remove extension and replace hyphens with spaces, capitalize words
    const name = fileName.replace('.html', '').replace(/-/g, ' ');
    return name.replace(/\b\w/g, c => c.toUpperCase());
}

// Recursively walk the project directory and process .html files
function walkAndReplace(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            // Skip the templates and scripts folders – they contain source files
            if (['templates', 'scripts', 'js', 'css', 'data'].includes(entry.name)) continue;
            walkAndReplace(fullPath);
        } else if (entry.isFile() && entry.name.endsWith('.html')) {
            // Read the placeholder content (may be minimal) – we only need the file name
            const pageTitle = titleFromFile(entry.name);
            const pageDescription = `Top-rated ${pageTitle} in New Zealand – find the best businesses.`;
            const pageUrl = `https://toprated.co.nz${fullPath.replace(/\\/g, '/').replace(/^.*\/toprated/, '')}`;

            // Replace placeholders in the template
            let finalHtml = baseTemplate
                .replace('<!-- PAGE_TITLE_PLACEHOLDER -->', pageTitle)
                .replace('<!-- PAGE_DESCRIPTION_PLACEHOLDER -->', pageDescription)
                .replace('<!-- PAGE_URL_PLACEHOLDER -->', pageUrl)
                .replace('<!-- PAGE_CONTENT_PLACEHOLDER -->', `<h1>${pageTitle}</h1><p>${pageDescription}</p>`);

            // Write back to the same file (overwrites placeholder)
            fs.writeFileSync(fullPath, finalHtml);
            console.log(`✅ Applied template to ${fullPath}`);
        }
    }
}

// Start from the project root (one level up from this script)
const projectRoot = path.resolve(__dirname, '..');
walkAndReplace(projectRoot);
console.log('✅ All placeholder pages have been upgraded to the base template.');
